project:
  type: website

website:
  title: "ANLAM LAB"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: team.qmd
        text: Team
      - href: publications.qmd
        text: Publications
      - href: datasets.qmd
        text: Datasets
      - href: contact.qmd
        text: Contact
    logo: img/icon_no_bg_white.png 

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



